shared_buffers = 64MB
effective_cache_size = 512MB
work_mem = 2MB
maintenance_work_mem = 32MB
max_connections = 20
autovacuum_max_workers = 2
max_worker_processes = 2
max_parallel_workers = 1
max_parallel_workers_per_gather = 1
